name: taxonomical-preparator
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pandas
  - plotly
  - pyinaturalist
  - pyinaturalist-convert
  - python-dotenv
  - python==3.10
  - tablib
  - pip
  - pip :
    - opentree
