name: taxonomical-preparator
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pandas
  - python
  - pip
  - pip :
    - opentree
    - pyinaturalist_convert
    - tablib
  - plotly
  - pyinaturalist
